enum Role {
    OWNER = "OWNER",
    PRESIDENT = "PRESIDENT",
    VICE_PRESIDENT = "VICE_PRESIDENT",
    SECRETARY = "SECRETARY",
    TREASURER = "TREASURER",
}

export const coOwner = [
    {
        role: Role.OWNER,
        name: "TEISSIER",
        address: "65 bd Wilson Churchill",
        emailMain: "jcdesalon@sfr.fr",
        emailOpt: "",
        lotNumber: 1,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "0670160943",
        officeId: 1,
        acquisitionDate: new Date("2022-01-01")
    },
    {
        role: Role.OWNER,
        name: "TEISSIER",
        address: "65 bd Wilson Churchill",
        emailMain: "jcdesalon2@sfr.fr",
        emailOpt: "",
        lotNumber: 2,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "0670160943",
        officeId: 1,
        acquisitionDate: new Date("2022-01-01")
    },
    {
        role: Role.OWNER,
        name: "TEISSIER",
        address: "65 bd Wilson Churchill",
        emailMain: "jcdesalon3@sfr.fr",
        emailOpt: "",
        lotNumber: 3,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "0670160943",
        officeId: 1,
        acquisitionDate: new Date("2022-01-01")
    },
    {
        role: Role.OWNER,
        name: "TEISSIER",
        address: "65 bd Wilson Churchill",
        emailMain: "jcdesalon4@sfr.fr",
        emailOpt: "",
        lotNumber: 4,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "0670160943",
        officeId: 1,
        acquisitionDate: new Date("2022-01-01")
    },
    {
        role: Role.OWNER,
        name: "FABRE",
        address: "549 chemin des massuguettes",
        emailMain: "fabre@gmail.com",
        emailOpt: "",
        lotNumber: 5,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-01-01")
    },
    {
        role: Role.OWNER,
        name: "RUAULT",
        address: "549 chemin des massuguettes",
        emailMain: "rjoe4@yahoo.fr",
        emailOpt: "",
        lotNumber: 6,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-06-01")
    },
    {
        role: Role.VICE_PRESIDENT,
        name: "BLANC",
        address: "549 chemin des massuguettes",
        emailMain: "alain.blanc868@orange.fr",
        emailOpt: "",
        lotNumber: 7,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-07-01")
    },
    {
        role: Role.OWNER,
        name: "JOBARD",
        address: "549 chemin des massuguettes",
        emailMain: "jobard.stephane@free.fr",
        emailOpt: "",
        lotNumber: 8,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-02-01")
    },
    {
        role: Role.OWNER,
        name: "CLEMENT",
        address: "549 chemin des massuguettes",
        emailMain: "clementphil13300@gmail.com",
        emailOpt: "clementvirg@gmail.com",
        lotNumber: 9,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-04-01")
    },
    {
        role: Role.OWNER,
        name: "CHIRADE / FARGEAS",
        address: "549 chemin des massuguettes",
        emailMain: "oceane_virginie@hotmail.com",
        emailOpt: "fargeas.sebastien.sf@gmail.com",
        lotNumber: 10,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-09-01")
    },
    {
        role: Role.PRESIDENT,
        name: "BROCHARD",
        address: "549 chemin des massuguettes",
        emailMain: "domibrochard@neuf.fr",
        emailOpt: "brochardpascale@neuf.fr",
        lotNumber: 11,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-01-01")
    },
    {
        role: Role.SECRETARY,
        name: "BARCELLO",
        address: "549 chemin des massuguettes",
        emailMain: "barcello.romain@gmail.com",
        emailOpt: "turchettilaurie@gmail.com",
        lotNumber: 12,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-06-01")
    },
    {
        role: Role.TREASURER,
        name: "CAILLEUX / AMIRI",
        address: "549 chemin des massuguettes",
        emailMain: "n.cailleux13@gmail.com",
        emailOpt: "amiri.sabine@orange.fr",
        lotNumber: 13,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-09-01")
    },
    {
        role: Role.OWNER,
        name: "REBEYREN",
        address: "549 chemin des massuguettes",
        emailMain: "david.rebeyren@orange.fr",
        emailOpt: "",
        lotNumber: 14,
        bankBalance: 0,
        city: "Salon de Provence",
        zipCode: "13300",
        phone: "",
        officeId: 1,
        acquisitionDate: new Date("2023-01-01")
    },
];
